name: Build melonDS (Windows ARM64/AArch64)

on:
  push:
    branches:
      - master

jobs:
  build-winarm64:
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-11-arm
    steps:
      - name: 'Configure git: core.autocrlf, core.eol'
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v5
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          pacboy: >-
            cmake:p
            enet:p
            faad2:p
            libarchive:p
            ninja:p
            qt5-static:p
            SDL2:p
            toolchain:p
            zstd:p
      - name: Build
        run: |
          cmake -S . -B build -DBUILD_STATIC=ON -DENABLE_JIT=OFF -DUSE_QT6=OFF -DUSE_VCPKG=OFF
          cmake --build build
      - name: Copy files
        run: |
          cd build
          mkdir upload
          cp ../LICENSE upload/license.txt
          cp melonDS.exe upload
          strip upload/melonDS.exe
      - name: Upload as artifact
        uses: actions/upload-artifact@v5
        with:
          name: melonDS-git-winarm64-${{github.sha}}
          path: build/upload
          if-no-files-found: error
